name: myenv
channels:
  - defaults
dependencies:
  - python=3.10.13
  - ultralytics=8.3.27
  - pytorch=2.6.0
  - matplotlib=3.8.2
  - pillow=10.1.0
  - opencv=4.10.0
  - pandas=2.1.3
  - numpy=1.26.4
  - scikit-image=0.22.0